# Configuration file for https://circleci.com/gh/oppia/foundation-website

# Note: YAML anchors allow an object to be re-used, reducing duplication.
# The ampersand declares an alias for an object, then later the `<<: *name`
# syntax dereferences it.
# See http://blog.daemonl.com/2016/02/yaml.html
# To validate changes, use an online parser, eg.
# http://yaml-online-parser.appspot.com/

# Variables

var_1: &docker_image circleci/python:2.7.15-browsers

# Default settings for each job
anchor_1: &job_defaults
  working_directory: ~/foundation-website
  docker:
    - image: *docker_image

version: 2
jobs:
  backend_tests:
    <<: *job_defaults

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: |
            bash scripts/setup.sh || exit 1
            bash scripts/setup_gae.sh || exit 1

      - run:
          name: Run tests
          command: |
            bash scripts/run_backend_tests.sh --generate_coverage_report

      - save_cache:
          key: *oppia_tools_cache_key
          paths:
            - ./oppia_tools/
  linter:
    <<: *job_defaults

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: |
            bash scripts/setup.sh || exit 1
            bash scripts/setup_gae.sh || exit 1

      - run:
          name: Run linter
          command: |
            bash scripts/run_linter.sh

workflows:
  version: 2
  circleci_tasks:
    jobs:
      - backend_tests
      - linter
